headers_training_data = [{"class": "quantity",
                          "sentence": "maximum max minimum quantity qyt amount"}, 
                          {"class": "price", "sentence": "maximum max minimum price charge fee payment value amount"},
                          {"class": "discount", "sentence": "discount reduction deduction dis"}, {"class": "sales", "sentence": "sales revenue amount"},
                          {"class": "location", "sentence": "location  loc place venue"},
                          {"class": "customer", "sentence": "customer cus"},
                          {"class": "id", "sentence": "id ref no number "},
                          {"class": "product", "sentence": "product item"}, 
                          {"class": "month", "sentence": "month m"}, 
                          {"class": "quarter", "sentence": "quarter qtr"},
                          {"class": "week", "sentence": "week"},
                          {"class": "days of week", "sentence": "days of week dow"}, 
                          {"class": "year", "sentence": "year  yr financial"},
                          {"class": "date", "sentence": "date time"},
                          {"class": "profit", "sentence": "profit"},
                          {"class": "cost", "sentence": "cost"}, 
                          {"class": "supplier", "sentence": "supp"},
                          {"class": "size", "sentence": "size"},
                          {"class": "gender", "sentence": "gender sex"},
                          {"class": "address", "sentence": "address add"},
                          {"class": "length", "sentence": "length lgt"},
                          {"class": "stores", "sentence": "stores"},
                          {"class": "customer", "sentence": "customer"}
                          ]


domain_training_data=[{"class":"sales", "sentence":"Store retailer country order method type retailer type product line product type product date quantity price customer id order id sales quotation order id price terms of delivery terms of payment  packaging date product description reorder level forecast "},
                      {"class":"sales","sentence":"actual difference gap target name address customer id age range gender item id brand id"},
                      {"class":"manufacturing", "sentence":"product manufacturer factory id ingrediants output machine id store id process time division date time quality materials inspections condition"},
                      {"class":"HR", "sentence":"leaves taken available leaves date time Date of hire dates employee employee name employee id date of birthAge leaves taken available leaves date time"},
                      {"class":"Finance/Accountancy", "sentence":"Net Sales Cost of Goods Sold Selling Expenses Administrative Expenses Other Income Other Expenses Beginning Inventory Inventory Purchased Inventory on Hand  Inventory Used Deflating Sales Labor  Factory overhead  Materials and supplies  Gross Margin"},
                      {"class":"Finance/Accountancy", "sentence":"Net operating profit Income Taxes Net Profit Direct Labor  Allowance Discounts current Assets non current assets current liabilities non current liabilities goodwill equity"},
                      {"class":"Finance/Accountancy", "sentence":"Cah and cash equavelance depreciation inventory investments loan id loan status effective date installmen interest income debtor id occupation payment date due amount"},
                      {"class":"Finance/Accountancy", "sentence":"creditor id occupation payment date amount to be paid warehouse location material quantity expiration Date inventory value vendor destination order quantity reorder time"},
                      {"class":"Finance/Accountancy", "sentence":"asset id asset cost date of aqusition depreciation net book value date of diposal expense type employee id department designation basic salary allowances deductions net salary gross salary"},
                      {"class":"Finance/Accountancy", "sentence":"date name item code amount paid cash out cash in  balance"},
                      {"class":"Marketing", "sentence":"price trade financial instrument  trading venue traders investors buyer seller Delivery method"},
                      {"class":"Marketing", "sentence":"Medium Media Strategy  Target audience Budget cost consultants Agencies Timeline Action"},
                      {"class":"Marketing", "sentence":"Comments Complaints satisfaction experience ratings"}]